apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zabbix-app: zabbix-agent
  name: zabbix-agent
spec:
  selector:
    matchLabels:
     zabbix-app: zabbix-agent
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        zabbix-app: zabbix-agent
    spec:    
      containers:
      - env:
        - name: ZBX_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              key: ZBX_SERVER_HOST
              name: zabbix-app

        - name: ZBX_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: ZBX_HOSTNAME
              name: zabbix-app

        image: zabbix/zabbix-agent:ubuntu-4.4.5
        name: zabbix-agent
        ports:
        - containerPort: 10050
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/zabbix/zabbix_agentd.d
          name: zabbix-agent-claim2
          readOnly: true
        - mountPath: /var/lib/zabbix/modules
          name: zabbix-agent-claim3
          readOnly: true
        - mountPath: /var/lib/zabbix/enc
          name: zabbix-agent-claim4
          readOnly: true
        - mountPath: /var/lib/zabbix/ssh_keys
          name: zabbix-agent-claim5
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: zabbix-agent-claim2
        persistentVolumeClaim:
          claimName: zabbix-agent-claim2
          readOnly: true
      - name: zabbix-agent-claim3
        persistentVolumeClaim:
          claimName: zabbix-agent-claim3
          readOnly: true
      - name: zabbix-agent-claim4
        persistentVolumeClaim:
          claimName: zabbix-agent-claim4
          readOnly: true
      - name: zabbix-agent-claim5
        persistentVolumeClaim:
          claimName: zabbix-agent-claim5
          readOnly: true
status: {}

### Service 
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    zabbix-app: zabbix-agent
  name: zabbix-agent
spec:
  ports:
  - name: "10050"
    port: 10050
    targetPort: 10050
  selector:
    zabbix-app: zabbix-agent
status:
  loadBalancer: {}

### PersistentVolumeClain2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
     zabbix-app: zabbix-agent
  name: zabbix-agent-claim2
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}

### PersistentVolumeClain3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
     zabbix-app: zabbix-agent
  name: zabbix-agent-claim3
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}

### PersistentVolumeClain4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
     zabbix-app: zabbix-agent
  name: zabbix-agent-claim4
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}

### PersistentVolumeClain5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
     zabbix-app: zabbix-agent
  name: zabbix-agent-claim5
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}





