apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wd2Q=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: MYSQL_ROOT_PASSWORD
  name: MYSQL_ROOT_PASSWORD
type: Opaque
