---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: aigent
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.7.5-standalone
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DESIGN
              value: "pappu687"
---

apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  namespace: aigent
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  ports:
    - port: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: adminer-aigent
  namespace: aigent
spec:
  rules:
  - host: adminer-aigent.lab.br
    http:
      paths:      
      - path: /
        backend:
          serviceName: adminer-svc
          servicePort: 8080