---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  namespace: aigent
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: zenatuz/nginx-aigent:0.0.1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: aigent
spec:
  selector:
    app: nginx
  ports:
    - port: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-aigent
  namespace: aigent
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: hello-aigent.lab.br
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-svc
              servicePort: 80
