apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: aigent
  labels:
    app: postgres
data:
  POSTGRES_DB: database
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
  namespace: aigent
provisioner: Local

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: aigent
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/pv-postgres/
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: aigent
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: aigent
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
  
---
  
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: aigent
  labels:
    app: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres